export const data = [
    {
        srNo: 34.0,
        name: "Keshavraj Multi Speciality Cooperative Hospital & Research Centre Ltd",
        address: "Kolhaour, Maharashtra",
        state: "MAHARASHTRA",
        district: "KOLHAPUR",
        dateOfRegistration: "27/04/2022",
        areaOfOperation: "Madhya Pradesh, Chhatisgarh, Jharkhan, Bihar",
        sectorType: "Health/Hospital",
      },
      {
        srNo: 35.0,
        name: "Vanashri Cooperative Power & Agro Progressive ltd",
        address: "Sangli , Maharashtra",
        state: "MAHARASHTRA",
        district: "SANGLI",
        dateOfRegistration: "26/04/2022",
        areaOfOperation: "Maharashtra, Gujarat, Rajasthan",
        sectorType: "Agro",
      },
      {
        srNo: 36.0,
        name: "Samrudh Marathwada Multi State\nVehicle Services Cooperative Society Ltd.",
        address: "Beed, maharashtra",
        state: "MAHARASHTRA",
        district: "BEED",
        dateOfRegistration: "20/04/2022",
        areaOfOperation: "Gujarat, Rajasthan",
        sectorType: "Others",
      },
      {
        srNo: 37.0,
        name: "Bharathiyajkl Machuwara Samudaay Cooperative Ltd.\n(BHARATHIJKLMASACO)",
        address: "Baramulla, Kashmir",
        state: "JAMMU AND KASHMIR",
        district: "BADGAM",
        dateOfRegistration: "18/04/2022",
        areaOfOperation: "Haryana, Delhi",
        sectorType: "Fisheries",
      },
      {
        srNo: 38.0,
        name: "Prestige Agro Multi State Cooperative Society Ltd",
        address: "Uttar Pradesh",
        state: "UTTAR PRADESH",
        district: "BULANDSHAHR",
        dateOfRegistration: "01/04/2022",
        areaOfOperation: "Haryana, Delhi, UttarPradesh, ",
        sectorType: "Agro",
      },
      {
        srNo: 39.0,
        name: "Vidhata Hamal Multi State Cooperative Society Ltd",
        address: "Bhandara, Maharashtra",
        state: "MAHARASHTRA",
        district: "BHANDARA",
        dateOfRegistration: "01/04/2022",
        areaOfOperation: "Uttrakhand, Himachal Pradesh, Jammu & Kashmir",
        sectorType: "Agro",
      },
      {
        srNo: 40.0,
        name: "Dr Appasahed Urf Sa. Re. Patil\nJayysinghpur Udgaon Sahakari Bank Ltd",
        address: "Kolhapur, maharashtra",
        state: "MAHARASHTRA",
        district: "KOLHAPUR",
        dateOfRegistration: "01/04/2022",
        areaOfOperation: "Maharashtra, Gujarat, Rajasthan",
        sectorType: "Cooperative Bank",
      },
      {
        srNo: 41.0,
        name: "Krushisadhna Mahila Multi State Agro Cooperative society Ltd",
        address: "Nashik maharashtra",
        state: "MAHARASHTRA",
        district: "NASIK",
        dateOfRegistration: "01/04/2022",
        areaOfOperation: "Haryana, Punjab, Rajasthan",
        sectorType: "Agro",
      },
      {
        srNo: 42.0,
        name: "Seva Sadan Multi Specialty\nCooperative Hospital and Research Center Ltd",
        address: "Gate no. 14, Chaitnya Complex, behind Tahsil karyalaya, Shrigonda Dist - Ahmednagar Pin -413701 (Maharashtra)",
        state: "MAHARASHTRA",
        district: "AHMEDNAGAR",
        dateOfRegistration: "21/03/2022",
        areaOfOperation: "Haryana, Rajasthan",
        sectorType: "Agro",
      },
      {
        srNo: 43.0,
        name: "Bulandshahr Agro MultiState cooperative Society Ltd",
        address: "Mohalla Mahadev, Galimpur Road, Dibai, Bulandshahr, Uttar Pradesh-202393",
        state: "UTTAR PRADESH",
        district: "BULANDSHAHR",
        dateOfRegistration: "21/03/2022",
        areaOfOperation: "Gujarat, Rajasthan, Haryana, Delhi",
        sectorType: "Agro",
      },
      {
        srNo: 44.0,
        name: "B K Dhanlakshmi Multi State Agro Cooperative Society Limited",
        address: "Mayflower signature, Office 7B, 7th Floor, Avinashi Road, Peelumedu, Coimbatore- 641004, Tamil Nadu",
        state: "TAMIL NADU",
        district: "COIMBATORE",
        dateOfRegistration: "08/03/2022",
        areaOfOperation: "Kerala, karnataka, Maharashtra, Gujarat",
        sectorType: "Agro",
      },
      {
        srNo: 45.0,
        name: "The Walmik Multi State Cooperative Handloom Weavers Cooperative Society Ltd",
        address: "Plot No 63, Aoodumbae, Gurudev nagar, Nandanavan, Hanuman Nagar, Nagpur 440009, Maharashtra",
        state: "MAHARASHTRA",
        district: "NAGPUR",
        dateOfRegistration: "21/02/2022",
        areaOfOperation: "Maharashtra, Karnataka, Tamil nadu",
        sectorType: "Industrial/Textile",
        "Unnamed: 8": "e"
      },
      {
        srNo: 46.0,
        name: "Ente Naadu Multi State Agro Co- operative Society Ltd.",
        address: "ST George High School, Aluva- Munnar Road, Kothamangalam, Ernakulam,\n686691, Kerala",
        state: "KERALA",
        district: "ERNAKULAM",
        dateOfRegistration: "03/02/2022",
        areaOfOperation: "Haryana, Gujarat, Maharashtra, Delhi",
        sectorType: "Agro",
      },
      {
        srNo: 47.0,
        name: "Rajsidhi Cooperative Cotton & Agro Industries Ltd",
        address: "Ahmednagar 414401, Maharashtra",
        state: "MAHARASHTRA",
        district: "AHMEDNAGAR",
        dateOfRegistration: "12/01/2022",
        areaOfOperation: "Maharashtra, Gujarat, Rajasthan",
        sectorType: "Agro",
      },
      {
        srNo: 48.0,
        name: "Natural Agro Farming Multi State Cooperative Society Ltd.",
        address: "D77, S/F, East of Kailash, New delhi 110065",
        state: "NEW DELHI",
        district: "NEW DELHI",
        dateOfRegistration: "12/01/2022",
        areaOfOperation: "Kerala, karnataka, Maharashtra, Gujarat",
        sectorType: "Agro",
      },
      {
        srNo: 49.0,
        name: "Mansa Development Cooperative Society Ltd",
        address: "41 Sukh Sagar, phase 4 colony, near Mittal College, Rasal, Kharod Bhopal 38, Madhya Pradesh",
        state: "MADHYA PRADESH",
        district: "BHOPAL",
        dateOfRegistration: "12/10/2021",
        areaOfOperation: "Haryana, Delhi",
        sectorType: "Agro",
      },
      {
        srNo: 50.0,
        name: "Om Agro Multi State Cooperative society Ltd",
        address: "Ahulana (Gohana) Sonipat Haryana 131301",
        state: "HARYANA",
        district: "SONIPAT",
        dateOfRegistration: "22/11/2021",
        areaOfOperation: "Haryana, Delhi",
        sectorType: "Agro",
      },
      {
        srNo: 51.0,
        name: "Ramchandra Multi Speciality Cooperative Hospital & Research Center Ltd",
        address: "S.No. 2/2, Near SBI bank, Savakar Colony, Islampur, Walwa, Sangli 415409,\nMaharashtra",
        state: "MAHARASHTRA",
        district: "SANGLI",
        dateOfRegistration: "10/11/2021",
        areaOfOperation: "Haryana, UttarPradesh, Himachal, Punjab",
        sectorType: "Health/Hospital",
      },
      {
        srNo: 52.0,
        name: "Mudra Agriculture & Skill Development Multistate Cooperative Society Ltd",
        address: "15-A, 3-4-757/22, APHB Building Near Raghavendra Swamy Temple Opposite Telangana Grameena Bank, Barkatputra, Hyderabad 500027",
        state: "TELANGANA",
        district: "ADILABAD",
        dateOfRegistration: "12/04/2017",
        areaOfOperation: "Bihar, West bengal, Odisha",
        sectorType: "Agro",
      },
      {
        srNo: 53.0,
        name: "The Bhuj Mercantile Coop. Bank Ltd",
        address: "Vyapar Bhawan, Mithakhali 6 Roads, Ahmedabad-380006(Gujarat)",
        state: "GUJARAT",
        district: "AHMADABAD",
        dateOfRegistration: "14/09/2021",
        areaOfOperation: "Tamil Nadu, karnataks",
        sectorType: "Cooperative Bank",
      },
      {
        srNo: 54.0,
        name: "Heaven Multi State Agro Cooperative Society Ltd",
        address: "Kh No 403, Babhani Nagar, Andar, Sominath Nagar, Ward No. 7, Deoria Kasiya Bypass Road, Deoria , Uttar Pradesh 274001",
        state: "UTTAR PRADESH",
        district: "MORADABAD",
        dateOfRegistration: "14/09/2021",
        areaOfOperation: "Haryana, Punajb",
        sectorType: "Agro",
      },
      {
        srNo: 55.0,
        name: "The Sutex Cooperative Bank Ltd",
        address: "Surjaram, Bachkaniwala Bhawan, Near Navjivan Circle, Udhana Magdalla Road, Surat 395017 Gujarat",
        state: "GUJARAT",
        district: "VALSAD",
        dateOfRegistration: "14/09/2021",
        areaOfOperation: "Manipur, Meghalaya",
        sectorType: "Cooperative Bank",
      },
      {
        srNo: 56.0,
        name: "The Navbharat Multi State Agro Farming and Marketing Cooperative Society Ltd",
        address: "Shop No 112, Floor-I, Sharda Arcade, Paliyad Road, Batod Gujarat",
        state: "GUJARAT",
        district: "BATOD",
        dateOfRegistration: "09/08/2021",
        areaOfOperation: "Maharashtra, Gujarat, Rajasthan",
        sectorType: "Agro",
      },
      {
        srNo: 57.0,
        name: "BharathiMana Fishermen development Cooperative Society ltd.\n(BHARATHIMANACO)",
        address: "Kha- Potshangham Maning, Leikai, PO & PS Bishnupur 795126 Manipur",
        state: "MANIPUR",
        district: "BISHNUPUR",
        dateOfRegistration: "06/07/2021",
        areaOfOperation: "Gujarat, Rajasthan",
        sectorType: "Fisheries",
      },
      {
        srNo: 58.0,
        name: "Agrovision Farmer Multi State Cooperative Society Ltd.",
        address: "H.No 3, Gate No 1, Krishna Colony, Near Universal School, Gorakhpur Kasya Road, Deoria, Uttar Pradesh 274001",
        state: "UTTAR PRADESH",
        district: "DEORIA",
        dateOfRegistration: "27/05/2021",
        areaOfOperation: "Maharashtra,Goa.Karnataka, Andhra Pradesh",
        sectorType: "Agro",
      },
      {
        srNo: 59.0,
        name: "Chitrakoot Multi State Agriculture Marketing Cooperative Society Ltd. (CMAMCS)",
        address: "H.No 104, Village & Post Sahewa, thana-\nGirwan, Tehsil Atarra, Banda, Uttar Pradesh 210120",
        state: "UTTAR PRADESH",
        district: "BANDA",
        dateOfRegistration: "29/04/2021",
        areaOfOperation: "Andhra Pradesh, Telangna",
        sectorType: "Agro",
      },
      {
        srNo: 60.0,
        name: "CP Agrotech Multi State Cooperative Society Ltd.",
        address: "C/O Manoj Kumar, Mohalla-Kannon Goyan, Kasba- Jhinjhana, Jhinjhana Rural, Shamli, Uttar Pradesh 247773",
        state: "UTTAR PRADESH",
        district: "MUZAFFARNAGAR",
        dateOfRegistration: "16/03/2021",
        areaOfOperation: "Madhya Pradesh, Chhatisgarh, Jharkhan, Bihar",
        sectorType: "Agro",
      },
      {
        srNo: 61.0,
        name: "Simplydesi Selfhelp Products, Processing and Marketing Multi State Cooperative Society Ltd",
        address: "52, Ananda Park Extension, East Punjabi Bagh, New Delhi 110026",
        state: "NEW DELHI",
        district: "NEW DELHI",
        dateOfRegistration: "24/02/2021",
        areaOfOperation: "Maharashtra, Gujarat, Rajasthan",
        sectorType: "Fisheries",
      },
      {
        srNo: 62.0,
        name: "Bharati North East Fisherman Co-operative Ltd. (BHARATICO)",
        address: "C/O Swambha Basumatary, near Simlaguri Post Office, Simlaguri, Dhaliagaon,\nChirang(BTR), Assam 783381",
        state: "ASSAM",
        district: "CHIRANG",
        dateOfRegistration: "15/02/2021",
        areaOfOperation: "Gujarat, Rajasthan",
        sectorType: "Fisheries",
      },
      {
        srNo: 63.0,
        name: "Chambal Agriculture Marketing Cooperative Ltd",
        address: "525, rajput Nagar, Bharouli road, Bhind, Madhya Pradesh 477001",
        state: "MADHYA PRADESH",
        district: "BHIND",
        dateOfRegistration: "15/01/2021",
        areaOfOperation: "Haryana, Delhi",
        sectorType: "Marketing",
      },
      {
        srNo: 64.0,
        name: "Sharda Agro Multi State Cooperative Society Ltd",
        address: "Bhopal, Madhya Pradesh",
        state: "MADHYA PRADESH",
        district: "BHOPAL",
        dateOfRegistration: "14/12/2020",
        areaOfOperation: "Haryana, Delhi, UttarPradesh, ",
        sectorType: "Agro",
      },
      {
        srNo: 65.0,
        name: "N E Railway Cooperative Credit Society Ltd,",
        address: "Chief Worshop Manager Office, NE Railway, Izzatnagar, Bareilly, Uttar Pradesh",
        state: "UTTAR PRADESH",
        district: "BAREILLY",
        dateOfRegistration: "24/11/2020",
        areaOfOperation: "Uttrakhand, Himachal Pradesh, Jammu & Kashmir",
        sectorType: "Credit",
      },
      {
        srNo: 66.0,
        name: "Ramraja Multi state Agro Cooperative Society ltd.",
        address: "102, Eligent Tower, Royal City, Shivpuri Road, Jhansi, 284003 Uttar Pradesh",
        state: "UTTAR PRADESH",
        district: "JHANSI",
        dateOfRegistration: "12/11/2020",
        areaOfOperation: "Maharashtra, Gujarat, Rajasthan",
        sectorType: "Agro",
      },
      {
        srNo: 67.0,
        name: "Vitthal Rao Shinde Sahakari Sahkar Karkhana Ltd",
        address: "Gangamainagar, Post Pimpalner, Taluka Madha, Solapur, 413210 Maharashtra",
        state: "MAHARASHTRA",
        district: "SOLAPUR",
        dateOfRegistration: "05/11/2020",
        areaOfOperation: "Haryana, Punjab, Rajasthan",
        sectorType: "Industrial/Textile",
      },
      {
        srNo: 68.0,
        name: "Ambika Multi State Health Service for the Weaker Section Cooperative Society Ltd",
        address: "Sai Illam, Floor-2, 53/2, Bharatheshwarar,\n3rd Street, Kodambakkam, Chennai 600024, Tamil Nadu",
        state: "TAMIL NADU",
        district: "CHENNAI",
        dateOfRegistration: "14/09/2020",
        areaOfOperation: "Haryana, Rajasthan",
        sectorType: "Agro",
      },
      {
        srNo: 69.0,
        name: "The UP Kisan Development cooperative Society Ltd",
        address: "65, Bheem Nagar, Vijay Khand 2, Gomti Nagar, Lucknow-226010, Uttar Pradesh",
        state: "UTTAR PRADESH",
        district: "LUCKNOW",
        dateOfRegistration: "10/08/2020",
        areaOfOperation: "Gujarat, Rajasthan, Haryana, Delhi",
        sectorType: "Agro",
      },
      {
        srNo: 70.0,
        name: "Farmtrade Agro Multi state Marketing Cooperative Ltd",
        address: "B-92. Mayfiels Garden Sector 48, Gurugram- 122002",
        state: "HARYANA",
        district: "GURGAON",
        dateOfRegistration: "10/08/2020",
        areaOfOperation: "Kerala, karnataka, Maharashtra, Gujarat",
        sectorType: "Marketing",
      },
      {
        srNo: 71.0,
        name: "Bihar State handloom Weavers Cooperative Union Ltd (BISHCOTEX)",
        address: "Handloom Bhawan, Rajendra Place, Patna, Bihar",
        state: "BIHAR",
        district: "PATNA",
        dateOfRegistration: "14/07/2020",
        areaOfOperation: "Maharashtra, Karnataka, Tamil nadu",
        sectorType: "Agro",
      },
      {
        srNo: 72.0,
        name: "Radhika Agricultural Cooperative Society Ltd",
        address: "Swami Puran Colony, Nai Basti, Jhansi 284002, Uttar Pradesh",
        state: "UTTAR PRADESH",
        district: "JHANSI",
        dateOfRegistration: "24/04/2020",
        areaOfOperation: "Haryana, Gujarat, Maharashtra, Delhi",
        sectorType: "Agro",
      },
      
      {
        srNo: 73.0,
        name: "Farm to Foreign Exports Entrepreneur Development Multi State Cooperative Society Ltd",
        address: "H.No. 6-9, Gundugolanu(P.O), Bhimadole (Mandal), Andhra Pradesh-534427",
        state: "ANDHRA PRADESH",
        district: "WEST GODAVARI",
        dateOfRegistration: "16/01/2020",
        areaOfOperation: "Haryana, UttarPradesh, Himachal, Punjab",
        sectorType: "Agro",
      },
      {
        srNo: 74.0,
        name: "Dharitri Jute and Eco Friendly Products Multi State Cooperative Society Ltd",
        address: "D.No.12-2-42111, Alapati Nagar, Gudimalkapur, Hyderabad-500028, Telangana",
        state: "TELANGANA",
        district: "ADILABAD",
        dateOfRegistration: "12/12/2019",
        areaOfOperation: "Bihar, West bengal, Odisha",
        sectorType: "Agro",
      },
      {
        srNo: 75.0,
        name: "The Malabar Multi State Agro Cooperative Society Limited",
        address: "1st Floor, Aiswarya Complex, Thavakkara, Kannur, Kerala- 670002",
        state: "KERALA",
        district: "KANNUR",
        dateOfRegistration: "20/10/2019",
        areaOfOperation: "Haryana, Punajb",
        sectorType: "Agro",
      },
      {
        srNo: 76.0,
        name: "Sai Raam Multi State Agri Cooperative Society Ltd",
        address: "No.6. (D-18), 6th Cross West Extension, Thillai Nagar, Trichy, Tamil Nadu-620008",
        state: "TAMIL NADU",
        district: "DHARMAPURI",
        dateOfRegistration: "06/12/2019",
        areaOfOperation: "Manipur, Meghalaya",
        sectorType: "Agro",
      },
      {
        srNo: 77.0,
        name: "Prabhavana Multi State Womens\u2019 Jute and Allied Fibre Products Cooperative Society Ltd",
        address: ", House. No 2-2-647/G/18/1, Near Shivam Road, DD Colony, Hyderabad, Telangana\n500013",
        state: "TELANGANA",
        district: "ADILABAD",
        dateOfRegistration: "27/09/2019",
        areaOfOperation: "Maharashtra, Gujarat, Rajasthan",
        sectorType: "Agro",
      },
      {
        srNo: 78.0,
        name: "The Gayatri Cooperative Urban Bank Ltd",
        address: "7-1,72, 73,74 Gayatri Towers, Tehsil Chowrasta, Jagtial Town, Dist. Jagtail, Telangana",
        state: "TELANGANA",
        district: "KARIMNAGAR",
        dateOfRegistration: "23/08/2019",
        areaOfOperation: "Gujarat, Rajasthan",
        sectorType: "Cooperative Bank",
      },
      {
        srNo: 79.0,
        name: "Shri Saibaba Multi State Cooperative Dudh Utpadak & Prakriya Sangh Ltd",
        address: "A/p Lohgaon, Tal- Rahata, Dist. Ahmednagar, PIN 413712 Maharashtra",
        state: "MAHARASHTRA",
        district: "AHMEDNAGAR",
        dateOfRegistration: "06/08/2019",
        areaOfOperation: "Maharashtra,Goa.Karnataka, Andhra Pradesh",
        sectorType: "Dairy",
      },
      {
        srNo: 80.0,
        name: "Subhiksha Organic Farmers Multi State Cooperative Society Ltd",
        address: "Krushi Nivasa, At Kuruvalli,Thirthahalli, Shimoga, Karnataka 577432",
        state: "KARNATAKA",
        district: "SHIMOGA",
        dateOfRegistration: "03/07/2019",
        areaOfOperation: "Andhra Pradesh, Telangna",
        sectorType: "Agro",
      },
      {
        srNo: 81.0,
        name: "The Panipat Urban Cooperative Bank Ltd (PUCB)",
        address: "510/8, G T Road,Panipat, Haryana 132103",
        state: "HARYANA",
        district: "PANIPAT",
        dateOfRegistration: "14/05/2019",
        areaOfOperation: "Madhya Pradesh, Chhatisgarh, Jharkhan, Bihar",
        sectorType: "Cooperative Bank",
      },
      {
        srNo: 82.0,
        name: "Green Earth Agro Cooperative Society Ltd",
        address: "3/170, Vishwas Khand, Gomti Society , Lucknow 226010, Uttar Pradesh",
        state: "UTTAR PRADESH",
        district: "LUCKNOW",
        dateOfRegistration: "03/05/2019",
        areaOfOperation: "Maharashtra, Gujarat, Rajasthan",
        sectorType: "Agro",
      },
      {
        srNo: 83.0,
        name: "Bihar Cooperative Federation Ltd",
        address: "Budh Marg, Patna 800001, Bihar",
        state: "BIHAR",
        district: "PATNA",
        dateOfRegistration: "03/10/2018",
        areaOfOperation: "Gujarat, Rajasthan",
        sectorType: "Agro",
      },
      {
        srNo: 84.0,
        name: "Bharathi Cooperative Housing Society Ltd",
        address: "87-A, Perambur High Road, Perambur Post, Chennai 600011 Tamil Nadu",
        state: "TAMIL NADU",
        district: "CHENNAI",
        dateOfRegistration: "18/05/2018",
        areaOfOperation: "Haryana, Delhi",
        sectorType: "Housing",
      },
      {
        srNo: 85.0,
        name: "The Surat People\u2019s Cooperative Bank Ltd",
        address: "Vasudhara Bhavan, Timalyawad, Nanpura, Surat, Gujarat",
        state: "GUJARAT",
        district: null,
        dateOfRegistration: "28/03/2018",
        areaOfOperation: "Haryana, Delhi, UttarPradesh, ",
        sectorType: "Cooperative Bank",
      },
      {
        srNo: 86.0,
        name: "Sanmati Sahakari Bank Ltd",
        address: "9/114, Laxmi Market, Ichalkaranji Kolhapur, Maharashtra 416115",
        state: "MAHARASHTRA",
        district: "JALGAON",
        dateOfRegistration: "27/03/2018",
        areaOfOperation: "Uttrakhand, Himachal Pradesh, Jammu & Kashmir",
        sectorType: "Cooperative Bank",
      },
      {
        srNo: 87.0,
        name: "Reserve Bank Staff & Officers cooperative Credit Society Ltd",
        address: "C/ Reserve Bank of India, Amar Building, 2nd Floor, Sir P Road, Fort, Mumbai,\n400001, Maharashtra",
        state: "MAHARASHTRA",
        district: "MUMBAI",
        dateOfRegistration: "13/02/2018",
        areaOfOperation: "Maharashtra, Gujarat, Rajasthan",
        sectorType: "Credit",
      },
      {
        srNo: 88.0,
        name: "Dev Lok Housing Cooperative Ltd",
        address: "A-55, Dwarka, Sector-19, New Delhi",
        state: "NEW DELHI",
        district: "NEW DELHI",
        dateOfRegistration: "02/02/2018",
        areaOfOperation: "Haryana, Punjab, Rajasthan",
        sectorType: "Housing",
      },
      {
        srNo: 89.0,
        name: "Maa Vaishno Agro Multi State Cooperative Society Ltd",
        address: "Shop No. 25, Block-A, Old LIC Building, Near BSNL Exchange, Super Market, Lalitpur,\n284403, Uttar Pradesh",
        state: "UTTAR PRADESH",
        district: "LALITPUR",
        dateOfRegistration: "19/01/2018",
        areaOfOperation: "Haryana, Rajasthan",
        sectorType: "Agro",
      },
      {
        srNo: 90.0,
        name: "Sree Balki Multi State Cooperative Housing Society Ltd",
        address: "No. 9, Elango Street, Kabilar, Nagar,\nManavala Nagar, Tiruvallur 602002, Tamil Nadu",
        state: "TAMIL NADU",
        district: "THIRUVALLUR",
        dateOfRegistration: "05/01/2018",
        areaOfOperation: "Gujarat, Rajasthan, Haryana, Delhi",
        sectorType: "Housing",
      },
      {
        srNo: 91.0,
        name: "Southern Multi State Agro Cooperative Society Ltd,",
        address: "27 Gokulam, Mount Pleasant Road, Conoor , Ooty, Tamil Nadu 643102",
        state: "TAMIL NADU",
        district: "COIMBATORE",
        dateOfRegistration: "19/12/2017",
        areaOfOperation: "Kerala, karnataka, Maharashtra, Gujarat",
        sectorType: "Agro",
      },
      {
        srNo: 92.0,
        name: "Dombivli Nagari Sahakari Bank Ltd",
        address: "Plot No P-52, MIDC Phase-II, Kalyan Shil Road, Dombovli (East) Maharashtra 421204",
        state: "MAHARASHTRA",
        district: "THANE",
        dateOfRegistration: "28/07/2017",
        areaOfOperation: "Maharashtra, Karnataka, Tamil nadu",
        sectorType: "Cooperative Bank",
      },
      {
        srNo: 93.0,
        name: "Lucknow Division Insurance Employees Cooperative Credit Society Ltd",
        address: "Jeevan Prakash Building, 30, Hazratganj , Lucknow, Uttar Pradesh 226001",
        state: "UTTAR PRADESH",
        district: "LUCKNOW",
        dateOfRegistration: "11/07/2017",
        areaOfOperation: "Haryana, Gujarat, Maharashtra, Delhi",
        sectorType: "Credit",
      },
      {
        srNo: 94.0,
        name: "The Kalyan Janata Sahakari Bank Ltd",
        address: "Kalyanam astu, Om Vijaykrishna, Apt, Adharwadi, Kalyan, West, Thane\nMaharashtra 421301",
        state: "MAHARASHTRA",
        district: "THANE",
        dateOfRegistration: "24/03/2017",
        areaOfOperation: "West bengal, Andhra Pradesh",
        sectorType: "Cooperative Bank",
      },
      {
        srNo: 95.0,
        name: "The Eastern Railway Employees\nCooperative Bank Limited (Eastern & North East Frontier Railway Employees Co-\noperative Bank Ltd.)",
        address: "17, Neta Ji Subhash Road, Kolkata 700001",
        state: "WEST BENGAL",
        district: "MALDAH",
        dateOfRegistration: "22/03/2017",
        areaOfOperation: "Maharashtra, Gujarat, Rajasthan",
        sectorType: null,
      },
      {
        srNo: 96.0,
        name: "Purvanchal Krishi Avam Kisan kalyan Multi State Cooperative Society Ltd",
        address: "House No. 799, Vill: Taraya Sujan, Post : Tarya Sujan, Block : Seorahi, Tehsil :\nTamkihi Raj, Dist. Kushinagar, Pin 274409,\nUttar Pradesh",
        state: "UTTAR PRADESH",
        district: "KUSHI NAGAR",
        dateOfRegistration: "06/03/2017",
        areaOfOperation: "Gujarat, Rajasthan, Haryana, Delhi",
        sectorType: "Agro",
      },
      {
        srNo: 97.0,
        name: "The Ajara Urban Cooperative Bank Limited",
        address: "393-B, Main Road Ajara, Kolhapur, 416505, Maharashtra",
        state: "MAHARASHTRA",
        district: "KOLHAPUR",
        dateOfRegistration: "17/02/2017",
        areaOfOperation: "Kerala, karnataka, Maharashtra, Gujarat",
        sectorType: "Cooperative Bank",
      },
      {
        srNo: 98.0,
        name: "Bihar State Housing Cooperative Federation Ltd",
        address: "Lalit Bhawan, Bailey Road, Patna , Bihar 800014",
        state: "BIHAR",
        district: "BUXAR",
        dateOfRegistration: "19/10/2016",
        areaOfOperation: "Maharashtra, Karnataka, Tamil nadu",
        sectorType: "Housing",
      },
      {
        srNo: 99.0,
        name: "The Navodit Cooperative Urban Thrift & Credit Society Ltd",
        address: "147, South Amarkali, Delhi 110051",
        state: "NEW DELHI",
        district: "NEW DELHI",
        dateOfRegistration: "27/09/2016",
        areaOfOperation: "Haryana, Gujarat, Maharashtra, Delhi",
        sectorType: "Credit",
      },
      {
        srNo: 100.0,
        name: "Lokseva Multi State Credit Cooperative Society Ltd",
        address: "A/p Tisgaon Pravara, Rahata, Ahmednagar 413712 Maharashtra",
        state: "MAHARASHTRA",
        district: "NAGPUR",
        dateOfRegistration: "26/09/2016",
        areaOfOperation: "West bengal, Andhra Pradesh",
        sectorType: "Credit",
      }
    ]
    
